(function() {
    'use strict';

    function factory($http, config) {
        var model = {};
        model = config;
        var arrayslide = [{
            Age: 27,
            AgeMax: null,
            Agemax: null,
            Agemin: null,
            // ApplicationPhotoPath: "~\Images\ProfilePics\KMPL_47098_Images\img2_Images\210470984_FullPhoto.jpg,~\Images\ProfilePics\KMPL_47098_Images\img3_Images\210470984_FullPhoto.jpg,~\Images\ProfilePics\KMPL_47098_Images\img1_Images\210470984_FullPhoto.jpg",
            Caste: "Telugu-Balija",
            CasteID: 403,
            Color: "Fair",
            Cust_ID: "47098",
            Cust_ProfileInterestsLog_ID: null,
            CustomerApplicationPhoto: null,
            CustomerFullPhoto: "http://d16o2fcjgzj2wp.cloudfront.net/Images/ProfilePics/KMPL_47098_Images/Img2_Images/210470984_FullPhoto.jpg",
            DOB: "24-May-1989",
            EduGroupnamenew: "--",
            Education: null,
            EducationGroup: "BE",
            Employeedin: null,
            FFNative: "Dindigul",
            FirstName: "R",
            FromTicketID: null,
            FromTicketIdSuf: "--",
            Gender: "Male",
            GenderID: null,
            Gothram: "THILAGA",
            Height: "5'8 in - 172 cms",
            HeightInCentimeters: 21,
            Heightmax: null,
            Heightmin: null,
            HoroscopePath: "--",
            HoroscopeStatus: 0,
            Income: "40000",
            Intercaste: false,
            IsConfidential: false,
            JobLocation: "Trichy",
            KMPLID: "TYBAM2314",
            LastName: "BAGESH PRABHU",
            MFNative: "Madurai",
            MaritalStatusID: 43,
            MaxHeight: null,
            MinHeight: null,
            Mystatus: "--",
            Name: null,
            NoOfBrothers: 1,
            NoOfSisters: 0,
            OppStatus: "--",
            Ownerflag: false,
            // Photo: "~\Images\ProfilePics\KMPL_47098_Images\img2_Images\210470984_FullPhoto.jpg",
            PhotoCount: 3,
            PhotoNames: "img2.jpg,img3.jpg,img1.jpg",
            PlaceOfBirth: "Madurai",
            Profession: "Admin Professional",
            ProfileID: "121333",
            ProfileStatusID: null,
            Property: "2500",
            RegistrationDate: null,
            Star: "Poorvashada",
            SubCaste: null,
            SuperConfidentila: 0,
            SurName: null,
            TOB: "20:30:00",
            ToTicketID: null,
            ToTicketIDSuf: "--",
            TotalRows: 498,
            TotalRowsKeyword: null,
            Totalpages: null,
            companyname: null,
            countrylivingin: "India",
            currency: "Rs",
            educationspecialisation: null,
            email: "rkkalp1960@gmail.com",
            fathercaste: "--",
            imageurl: null,
            maritalstatus: "Unmarried",
            mothercaste: "--",
            mothertongue: null,
            paid: 1,
            serviceDate: ""
        }, {
            Age: 27,
            AgeMax: null,
            Agemax: null,
            Agemin: null,
            //ApplicationPhotoPath: "~\Images\ProfilePics\KMPL_47098_Images\img2_Images\210470984_FullPhoto.jpg,~\Images\ProfilePics\KMPL_47098_Images\img3_Images\210470984_FullPhoto.jpg,~\Images\ProfilePics\KMPL_47098_Images\img1_Images\210470984_FullPhoto.jpg",
            Caste: "Telugu-Balija",
            CasteID: 403,
            Color: "Fair",
            Cust_ID: "47098",
            Cust_ProfileInterestsLog_ID: null,
            CustomerApplicationPhoto: null,
            CustomerFullPhoto: "http://d16o2fcjgzj2wp.cloudfront.net/Images/ProfilePics/KMPL_47098_Images/Img2_Images/210470984_FullPhoto.jpg",
            DOB: "24-May-1989",
            EduGroupnamenew: "--",
            Education: null,
            EducationGroup: "BE",
            Employeedin: null,
            FFNative: "Dindigul",
            FirstName: "R",
            FromTicketID: null,
            FromTicketIdSuf: "--",
            Gender: "Male",
            GenderID: null,
            Gothram: "THILAGA",
            Height: "5'8 in - 172 cms",
            HeightInCentimeters: 21,
            Heightmax: null,
            Heightmin: null,
            HoroscopePath: "--",
            HoroscopeStatus: 0,
            Income: "40000",
            Intercaste: false,
            IsConfidential: false,
            JobLocation: "Trichy",
            KMPLID: "TYBAM2314",
            LastName: "BAGESH PRABHU",
            MFNative: "Madurai",
            MaritalStatusID: 43,
            MaxHeight: null,
            MinHeight: null,
            Mystatus: "--",
            Name: null,
            NoOfBrothers: 1,
            NoOfSisters: 0,
            OppStatus: "--",
            Ownerflag: false,
            //  Photo: "~\Images\ProfilePics\KMPL_47098_Images\img2_Images\210470984_FullPhoto.jpg",
            PhotoCount: 3,
            PhotoNames: "img2.jpg,img3.jpg,img1.jpg",
            PlaceOfBirth: "Madurai",
            Profession: "Admin Professional",
            ProfileID: "210470984",
            ProfileStatusID: null,
            Property: "2500",
            RegistrationDate: null,
            Star: "Poorvashada",
            SubCaste: null,
            SuperConfidentila: 0,
            SurName: null,
            TOB: "20:30:00",
            ToTicketID: null,
            ToTicketIDSuf: "--",
            TotalRows: 498,
            TotalRowsKeyword: null,
            Totalpages: null,
            companyname: null,
            countrylivingin: "India",
            currency: "Rs",
            educationspecialisation: null,
            email: "rkkalp1960@gmail.com",
            fathercaste: "--",
            imageurl: null,
            maritalstatus: "Unmarried",
            mothercaste: "--",
            mothertongue: null,
            paid: 1,
            serviceDate: ""
        }];
        model.totalRecords = arrayslide[0].TotalRows;
        model.setSlides(arrayslide);
        model.slide = function(old, news) {

            console.log(news);
            if (news === 1) {
                arrayslide[0].ProfileID = Math.random();
                arrayslide[1].ProfileID = Math.random();
                model.addSlides(arrayslide);
            }
        };
        return model;
    }
    angular
        .module('Kaakateeya')
        .factory('bootstrapSlideModel', factory);
    factory.$inject = ['$http', 'complex-slide-config'];
})();