 (function(angular) {
     'use strict';

     function Controller(dashboardModel, scope) {
         var vm = this,
             model;
         vm.init = function() {
             vm.model = model = dashboardModel;
             model.slideshowfunction(false);
         };

         vm.init();

         vm.slideshowfunction = function(flag, empid, branchcode, frompage, topage, tablename, type, array, slideflag) {
             model.slideshowfunction(flag, empid, branchcode, frompage, topage, tablename, type, array, slideflag);
             scope.$broadcast("slideshowdynamic");
         };

         vm.testarray = [{ "Row": 1, "Cust_ID": "53189", "ProfileID": "110531892", "TotalRows": 5, "Totalpages": 1, "KMPLID": "HA", "IsConfidential": false, "FirstName": "NARIPEDDI", "LastName": "SIVARAMA KRISHNA", "Gender": "Male", "DOB": "12-Apr-1987", "Caste": "Kamma", "SubCaste": null, "Age": 30, "Height": "5'11 in - 180 cms", "Color": "Fair", "EducationGroup": "BTech", "Profession": "Engineer - Non IT", "JobLocation": "DOHA", "MotherTongue": "Telugu", "CountryLivingin": "India", "MaritalStatus": "Unmarried", "Star": "Uttara", "Gothram": "MERUGUNOLLA", "TOB": "10:15:00", "EduSpecialization": "Civil", "EduGroupnamenew": null, "EmployeedIn": "Private Company", "ProfGroup": "IT & Engineering", "Property": 200, "Income": "250000", "Religion": "Hindu", "VisaStatus": null, "ArrivalDate": null, "DepartureDate": null, "FFNative": "Guntur", "MFNative": "Prakasam", "FFDistrict": "Guntur", "FMDistrict": "Prakasam", "CompanyName": "", "LastLoginDT": null, "Citizenship": "India", "University": null, "Padam": "3", "ManglikKujadosham": "No", "NoOfBrothers": 1, "NoOfSisters": 1, "DOR": "15-Nov-2012", "PlaceOfBirth": "Ongole", "Photo": "~\\Images\\ProfilePics\\KMPL_53189_Images\\img2_Images\\110531892_FullPhoto.jpg", "PhotoCount": 3, "PhotoNames": "img2.jpg,img3.jpg,img1.jpg", "ApplicationPhotoPath": "~\\Images\\ProfilePics\\KMPL_53189_Images\\img2_Images\\110531892_FullPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img3_Images\\110531892_FullPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img1_Images\\110531892_FullPhoto.JPG", "FullPath": "~\\Images\\ProfilePics\\KMPL_53189_Images\\img2_Images\\110531892_FullPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img3_Images\\110531892_FullPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img1_Images\\110531892_FullPhoto.JPG", "PhoneNumber": "", "ReviewedPhotoStatus": 2, "PhotoPasswordFlag": 0, "GenderID": 1, "ApplicationPhotoPath1": "~\\Images\\ProfilePics\\KMPL_53189_Images\\img2_Images\\110531892_ApplicationPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img3_Images\\110531892_ApplicationPhoto.jpg,~\\Images\\ProfilePics\\KMPL_53189_Images\\img1_Images\\110531892_ApplicationPhoto.JPG", "HoroscopeStatus": 0, "HoroscopePath": null, "currency": "Rs", "email": "jayakrishna.naripeddi@gmail.com", "number": "9848547745", "paid": true, "Intercaste": false, "fathercaste": null, "mothercaste": null, "HeightInCentimeters": 24, "SuperConfidentila": false, "onlinepaymnetcount": 1, "offlinepaymnetcount": 0, "offlineexpiry": "2016-09-01T00:00:00", "onlineexpiry": "2015-10-10T00:00:00", "UploadedPhotoscount": 3, "PhotoshopCount": 3, "ProfileGrade": null, "IsPaidMember": 0, "Ownerflag": true, "OwnerName": "admin", "RegistrationDate": "15 Nov 2012 00:00:00", "CreatedDate": "19 Dec 2016 10:19:37", "onlinepaid": "OP", "onlinepaidcls": "Dark", "offlinepaid": "KU", "offlinepaidcls": "light" },
             { "Row": 2, "Cust_ID": "52293", "ProfileID": "210522935", "TotalRows": 5, "Totalpages": 1, "KMPLID": "VM", "IsConfidential": false, "FirstName": "KAPU", "LastName": "VENKATA LAKSHMI PRASAD", "Gender": "Male", "DOB": "25-May-1971", "Caste": "Padmasali", "SubCaste": null, "Age": 46, "Height": "5'9 in - 175 cms", "Color": "Fair", "EducationGroup": "BTech", "Profession": "Software Professional", "JobLocation": "HOUSTON", "MotherTongue": "Telugu", "CountryLivingin": "USA", "MaritalStatus": "Unmarried", "Star": "Poorvabadra", "Gothram": "MARKANDEYA", "TOB": "10:30:00", "EduSpecialization": "Civil", "EduGroupnamenew": null, "EmployeedIn": "Private Company", "ProfGroup": "IT & Engineering", "Property": 150, "Income": "0", "Religion": "Hindu", "VisaStatus": "Work Permit", "ArrivalDate": null, "DepartureDate": null, "FFNative": "Visakhapatnam", "MFNative": "Visakhapatnam", "FFDistrict": "Visakhapatnam", "FMDistrict": "Visakhapatnam", "CompanyName": "", "LastLoginDT": null, "Citizenship": "India", "University": null, "Padam": null, "ManglikKujadosham": "No", "NoOfBrothers": 1, "NoOfSisters": 1, "DOR": "08-Apr-2008", "PlaceOfBirth": "Visakhapatnam", "Photo": null, "PhotoCount": 0, "PhotoNames": null, "ApplicationPhotoPath": null, "FullPath": null, "PhoneNumber": "", "ReviewedPhotoStatus": null, "PhotoPasswordFlag": 0, "GenderID": 1, "ApplicationPhotoPath1": null, "HoroscopeStatus": 0, "HoroscopePath": null, "currency": "US", "email": "raviflute@gmail.com", "number": "9848891219", "paid": true, "Intercaste": false, "fathercaste": null, "mothercaste": null, "HeightInCentimeters": 22, "SuperConfidentila": false, "onlinepaymnetcount": 0, "offlinepaymnetcount": 1, "offlineexpiry": "2012-06-04T00:00:00", "onlineexpiry": null, "UploadedPhotoscount": 0, "PhotoshopCount": 0, "ProfileGrade": 1, "IsPaidMember": 0, "Ownerflag": true, "OwnerName": "admin", "RegistrationDate": "08 Apr 2008 00:00:00", "CreatedDate": "25 Sep 2016 15:27:01", "onlinepaid": "OU", "onlinepaidcls": "light", "offlinepaid": "KP", "offlinepaidcls": "Dark" },
             { "Row": 3, "Cust_ID": "38416", "ProfileID": "010384161", "TotalRows": 5, "Totalpages": 1, "KMPLID": "NE", "IsConfidential": false, "FirstName": "ROUTHU", "LastName": "SRIDHAR", "Gender": "Male", "DOB": "01-Jan-1977", "Caste": "Kapu", "SubCaste": null, "Age": 40, "Height": "5'11 in - 180 cms", "Color": "Fair", "EducationGroup": "BE", "Profession": "Manager", "JobLocation": "TORONTO", "MotherTongue": "Telugu", "CountryLivingin": "Canada", "MaritalStatus": "Unmarried", "Star": null, "Gothram": "NAGESWARA", "TOB": "12:00:00", "EduSpecialization": "Electronics", "EduGroupnamenew": null, "EmployeedIn": "Private Company", "ProfGroup": "Accounting / Banking / Finance", "Property": null, "Income": "9000", "Religion": "Hindu", "VisaStatus": "Work Permit", "ArrivalDate": null, "DepartureDate": null, "FFNative": "Hyderabad", "MFNative": "Hyderabad", "FFDistrict": "Hyderabad", "FMDistrict": "Hyderabad", "CompanyName": "", "LastLoginDT": null, "Citizenship": "India", "University": null, "Padam": null, "ManglikKujadosham": "yes", "NoOfBrothers": 1, "NoOfSisters": 0, "DOR": "17-Jan-2013", "PlaceOfBirth": "Not Given", "Photo": null, "PhotoCount": 0, "PhotoNames": null, "ApplicationPhotoPath": null, "FullPath": null, "PhoneNumber": "", "ReviewedPhotoStatus": null, "PhotoPasswordFlag": 0, "GenderID": 1, "ApplicationPhotoPath1": null, "HoroscopeStatus": 0, "HoroscopePath": null, "currency": "CAD", "email": "rkmohan1@yahoo.com", "number": "8179806670", "paid": true, "Intercaste": false, "fathercaste": null, "mothercaste": null, "HeightInCentimeters": 24, "SuperConfidentila": false, "onlinepaymnetcount": 0, "offlinepaymnetcount": 1, "offlineexpiry": "2015-09-02T00:00:00", "onlineexpiry": null, "UploadedPhotoscount": 0, "PhotoshopCount": 0, "ProfileGrade": 3, "IsPaidMember": 0, "Ownerflag": true, "OwnerName": "admin", "RegistrationDate": "17 Jan 2013 00:00:00", "CreatedDate": "27 Jan 2017 11:43:49", "onlinepaid": "OU", "onlinepaidcls": "light", "offlinepaid": "KP", "offlinepaidcls": "Dark" },
             { "Row": 4, "Cust_ID": "11977", "ProfileID": "110119776", "TotalRows": 5, "Totalpages": 1, "KMPLID": "HD", "IsConfidential": false, "FirstName": "KODALI", "LastName": "KRANTHI KUMAR", "Gender": "Male", "DOB": "16-Jun-1982", "Caste": "Kamma", "SubCaste": null, "Age": 35, "Height": "6'2 in - 188 cms", "Color": "Fair", "EducationGroup": null, "Profession": null, "JobLocation": null, "MotherTongue": "Telugu", "CountryLivingin": "USA", "MaritalStatus": "Unmarried", "Star": "Revathi", "Gothram": "SIGUNOLLA", "TOB": "18:45:00", "EduSpecialization": null, "EduGroupnamenew": null, "EmployeedIn": null, "ProfGroup": null, "Property": null, "Income": null, "Religion": "Hindu", "VisaStatus": "Work Permit", "ArrivalDate": null, "DepartureDate": null, "FFNative": "Guntur", "MFNative": null, "FFDistrict": "Guntur", "FMDistrict": null, "CompanyName": "", "LastLoginDT": null, "Citizenship": "India", "University": null, "Padam": null, "ManglikKujadosham": "No", "NoOfBrothers": null, "NoOfSisters": null, "DOR": "09-Jul-2010", "PlaceOfBirth": "Repalle ", "Photo": "~\\Images\\ProfilePics\\KMPL_11977_Images\\img1_Images\\110119776_FullPhoto.jpg", "PhotoCount": 1, "PhotoNames": "img1.Jpg", "ApplicationPhotoPath": "~\\Images\\ProfilePics\\KMPL_11977_Images\\img1_Images\\110119776_FullPhoto.jpg", "FullPath": "~\\Images\\ProfilePics\\KMPL_11977_Images\\img1_Images\\110119776_FullPhoto.jpg", "PhoneNumber": "", "ReviewedPhotoStatus": 2, "PhotoPasswordFlag": 0, "GenderID": 1, "ApplicationPhotoPath1": "~\\Images\\ProfilePics\\KMPL_11977_Images\\img1_Images\\110119776_ApplicationPhoto.jpg", "HoroscopeStatus": 0, "HoroscopePath": null, "currency": null, "email": "chowdaryraok@yahoo.co.in", "number": "9490950137", "paid": true, "Intercaste": false, "fathercaste": null, "mothercaste": null, "HeightInCentimeters": 27, "SuperConfidentila": false, "onlinepaymnetcount": 1, "offlinepaymnetcount": 1, "offlineexpiry": "2013-12-05T00:00:00", "onlineexpiry": "2014-01-24T00:00:00", "UploadedPhotoscount": 1, "PhotoshopCount": 1, "ProfileGrade": null, "IsPaidMember": 0, "Ownerflag": true, "OwnerName": "admin", "RegistrationDate": "09 Jul 2010 00:00:00", "CreatedDate": "13 Mar 2016 16:09:25", "onlinepaid": "OP", "onlinepaidcls": "Dark", "offlinepaid": "KP", "offlinepaidcls": "Dark" },
             { "Row": 5, "Cust_ID": "11959", "ProfileID": "110119599", "TotalRows": 5, "Totalpages": 1, "KMPLID": "HD", "IsConfidential": false, "FirstName": "KODALI", "LastName": "RAMA", "Gender": "Female", "DOB": "19-May-1989", "Caste": "Kamma", "SubCaste": null, "Age": 28, "Height": "5'8 in - 172 cms", "Color": "Fair", "EducationGroup": null, "Profession": null, "JobLocation": null, "MotherTongue": "Telugu", "CountryLivingin": "Australia", "MaritalStatus": "Unmarried", "Star": null, "Gothram": "SIKINOLLA", "TOB": "12:00:00", "EduSpecialization": null, "EduGroupnamenew": null, "EmployeedIn": null, "ProfGroup": null, "Property": null, "Income": null, "Religion": "Hindu", "VisaStatus": "Citizen", "ArrivalDate": null, "DepartureDate": null, "FFNative": "Krishna", "MFNative": null, "FFDistrict": "Krishna", "FMDistrict": null, "CompanyName": "", "LastLoginDT": null, "Citizenship": "India", "University": null, "Padam": null, "ManglikKujadosham": "No", "NoOfBrothers": null, "NoOfSisters": null, "DOR": "21-Jul-2013", "PlaceOfBirth": "Not Given", "Photo": "~\\Images\\ProfilePics\\KMPL_11959_Images\\img1_Images\\110119599_FullPhoto.jpg", "PhotoCount": 1, "PhotoNames": "img1.Jpg", "ApplicationPhotoPath": "~\\Images\\ProfilePics\\KMPL_11959_Images\\img1_Images\\110119599_FullPhoto.jpg", "FullPath": "~\\Images\\ProfilePics\\KMPL_11959_Images\\img1_Images\\110119599_FullPhoto.jpg", "PhoneNumber": "", "ReviewedPhotoStatus": 2, "PhotoPasswordFlag": 0, "GenderID": 2, "ApplicationPhotoPath1": "~\\Images\\ProfilePics\\KMPL_11959_Images\\img1_Images\\110119599_ApplicationPhoto.jpg", "HoroscopeStatus": 0, "HoroscopePath": null, "currency": null, "email": "DEL.k000666m@hotmail.com", "number": "6298361714", "paid": true, "Intercaste": null, "fathercaste": null, "mothercaste": null, "HeightInCentimeters": 21, "SuperConfidentila": false, "onlinepaymnetcount": 0, "offlinepaymnetcount": 1, "offlineexpiry": "2015-03-10T00:00:00", "onlineexpiry": null, "UploadedPhotoscount": 1, "PhotoshopCount": 1, "ProfileGrade": null, "IsPaidMember": 0, "Ownerflag": true, "OwnerName": "admin", "RegistrationDate": "21 Jul 2013 00:00:00", "CreatedDate": "14 Jun 2016 17:09:43", "onlinepaid": "OU", "onlinepaidcls": "light", "offlinepaid": "KP", "offlinepaidcls": "Dark" }
         ];

     }
     angular.module('Kaakateeya').controller('dashboardCtrl', ['dashboardModel', '$scope', Controller]);

 })(angular);